image:
  file: .gitpod.Dockerfile

tasks:
  - init: remote-web-adb/gitpod-adb init
    command: remote-web-adb/gitpod-adb &> .remote-web-adb.log

ports:
  - port: 8080
    onOpen: ignore
  - port: 5555
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 5037
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter@3.19.0:/MRpX1iDrjzN++URaPj9kw==
    - dart-code.dart-code@3.19.2:aq53Ov11OfEpp/BTf5TPEA==